# Generated by Django 3.1.4 on 2020-12-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_auto_20201221_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('fase', models.CharField(choices=[('R', 'R'), ('S', 'S'), ('T', 'T'), ('NE', 'Não Especificado')], max_length=2)),
                ('disjuntor', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('NE', 'Não Especificado')], max_length=2)),
                ('descricao', models.CharField(max_length=150)),
                ('corrente', models.IntegerField(blank=True, default=0)),
                ('equipamento', models.ManyToManyField(to='cliente.Equipamento')),
            ],
        ),
    ]
