# Generated by Django 3.1.4 on 2020-12-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20201222_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordpu',
            name='f60',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordpu',
            name='h',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordpu',
            name='mcnt',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordpu',
            name='t',
            field=models.FloatField(default=0),
        ),
    ]
