# Generated by Django 3.1.4 on 2021-01-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateway',
            options={'verbose_name': 'gateway', 'verbose_name_plural': 'gateways'},
        ),
    ]
