# Generated by Django 3.1.4 on 2020-12-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20)),
                ('razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=200)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('serv_descarga_parcial', models.BooleanField(default=False)),
                ('serv_temperatura', models.BooleanField(default=False)),
                ('contato1_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('contato1_setor', models.CharField(blank=True, max_length=150, null=True)),
                ('contato1_fone', models.CharField(blank=True, max_length=150, null=True)),
                ('contato1_email', models.CharField(blank=True, max_length=150, null=True)),
                ('contato2_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('contato2_setor', models.CharField(blank=True, max_length=150, null=True)),
                ('contato2_fone', models.CharField(blank=True, max_length=150, null=True)),
                ('contato2_email', models.CharField(blank=True, max_length=150, null=True)),
                ('email_alerta', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.planta', verbose_name='plantas')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('temperatura_max', models.IntegerField(blank=True, default=0)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.setor', verbose_name='setores')),
            ],
        ),
    ]
