# Generated by Django 3.1.4 on 2020-12-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name': 'equipamento', 'verbose_name_plural': 'equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name': 'planta', 'verbose_name_plural': 'plantas'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'setor', 'verbose_name_plural': 'setores'},
        ),
    ]
